### ISSUE TITLE
can't add hackatime to github workflows

### ISSUE THREAD

**Issue by Toni500github** [hackclub/hackatime-legacy#30]
wanted to add hackatime to my waka-readme github worflow but it fails with the error:\
`time data '2025-02-07T17:38:22.027Z' does not match format '%Y-%m-%dT%H:%M:%SZ'`

reference to https://github.com/athul/waka-readme/issues/112:
> From the official WakaTime API we're expecting date-time in `'%Y-%m-%dT%H:%M:%SZ'` format. eg. `'2022-02-20T18:29:59Z'`.
> 
> Your instance of WakaAPI provides `2022-11-27T01:50:21.284Z`, which has millisecond resolution. Please adjust the settings of your self-hosted instance to match `'%Y-%m-%dT%H:%M:%SZ'` format. Ref: [`https://strftime.org/`](https://strftime.org/)

my `.github/workflows/waka-readme.yml`
```yaml
name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
        # this action name
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          ### meta
          API_BASE_URL: https://waka.hackclub.com/api # optional
          ### content
          SHOW_TITLE: true # optional
          BLOCKS: -> # optional
          TIME_RANGE: all_time # optional
          LANG_COUNT: 10 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: false # optional
          STOP_AT_OTHER: true # optional
          IGNORED_LANGUAGES: YAML JSON # optional
          ### commit
          TARGET_BRANCH: master # optional
          TARGET_PATH: README.md # optional
          AUTHOR_NAME: Toni500github # optional
```
